### PR TITLE
✏️ Remove spelling mistakes in files that reference 'Extensions.cs'

### PR DESCRIPTION
**Pull request by Lamparter**
### 📄 Description

Remove incorrectly spelt 'Extentions' in favour of 'Extensions', the correctly spelt alternative. First noticed in #19 but never resolved.

### ✅ Tasks

```[tasklist]
### Remove 'Extentions' and all its references
- [x] Remove all references to the word 'Extentions'
- [ ] Reference 'Extentions.cs' in project/other required references
- [ ] Replace filenames including 'Extentions' with 'Extensions'
```

### CODE REVIEW

**Comment by Lamparter** [comment]
@NoobNotFound I think that's all the references but I could be wrong...

**Comment by NoobNotFound** [comment]
> @NoobNotFound I think that's all the references but I could be wrong...

I'll see

**Comment by NoobNotFound** [comment]
I think that's it, I don't see any other typos and the building project succeeded. I think we should merge.

**Comment by Lamparter** [comment]
Just checked - it builds correctly. Merging now.

**Pull request merged**
